[package]
name = "jlox"
version = "0.1.0"
authors = ["Ian Smith <smith.ian@husky.neu.edu>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
lazy_static = "1.3.0"

[[bin]]
name = "jlox"
path = "src/bin/main.rs"

[lib]
name = "libjlox"
path = "src/lib.rs"